### ISSUE TITLE
Queues Disappear

### ISSUE THREAD

**Issue by articleinnovations** [smrchy/rsmq#129]
After some period of time, it looks like (empty) queues disappear from Redis. Perhaps this is some kind of setting in the Redis server, or is it that the queues need to have messages published regularly? If so, what is the timeout, and is that configurable?

Here is an error message received when adding a message to a queue that disappeared:

{
    "cause": {
        "name": "queueNotFound",
        "message": "Queue not found"
    },
    "isOperational": true
}

**Comment by rcldesign** [comment]
After further investigation, I am able to duplicate this bug 100% of the time. 

Using this node script:

`const redis = require('redis');
const RedisSMQ = require('rsmq-promise');

const qname = `test-${Math.round(Math.random() * 100000)}`;
console.log(`Queue Name: ${qname}`);

const rsmq = new RedisSMQ({
    host: 'localhost',
    port: 6379,
    ns: 'dl',
    realtime: true,
});

let msgCnt = 0;

let queueSubscription = redis.createClient();
queueSubscription.on('message', () => {
    try {
        rsmq.receiveMessage({ qname }).then((msg) => {
            if (!msg.id) {
                console.log('Received empty message');
                return;
            }
            const { value } = JSON.parse(msg.message);
            console.log(`[${(new Date()).toISOString()}] 1s Received message ${value}`);
            return rsmq.deleteMessage({ qname, id: msg.id }).catch(error => {
                console.log(`[${(new Date()).toISOString()}] 1s Error deleting object from queue: ${error}`);
                process.exit(0);
            });
        })
        
        .catch(error => {
            console.log(`[${(new Date()).toISOString()}] 1s Error receiving object from queue: ${error}`);
            process.exit(0);
        });
    } catch (error) { 
        console.log(`[${(new Date()).toISOString()}] 1s Error receiving or deleting object from queue: ${error}`);
        process.exit(0);
    }
});

rsmq.createQueue({
    qname,
    vt: 60,
    delay: 0,
    maxsize: -1,
}).then(() => {
    queueSubscription.subscribe(`dl:rt:${qname}`);
});

setTimeout(() => {
    setInterval(() => {
        msgCnt += 1;
        console.log(`[${(new Date()).toISOString()}] 1s Sending message ${msgCnt}`);
        try {
            rsmq.sendMessage({
                qname,
                message: JSON.stringify({
                    type: 'test',
                    value: msgCnt,
                    time: new Date(),
                    message: 'This is a test of something',
                }),
            }).catch(error => {
                console.log(`[${(new Date()).toISOString()}] 1s Error inserting object in to queue: ${error}`);
                process.exit(0);
            });
        } catch (error) {
            console.log(`[${(new Date()).toISOString()}] 1s Error inserting object in to queue: ${error}`);
            process.exit(0);
        }
    }, 1000);
}, 10000);
`
After approx. 10k seconds, the application will eventually catch an error (in this instance it happened when trying to insert the 10411th item in to the queue (and since an item is inserted every second, that would be after running for 10411 seconds)

[2020-11-17T23:09:42.385Z] 1s Error inserting object in to queue: queueNotFound: Queue not found

At this point in time, I did a redis-cli info to get information about redis' current state:

`# Server
redis_version:3.2.12
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:b2d74fe5fff7657d
redis_mode:standalone
os:Linux 4.14.193-149.317.amzn2.x86_64 x86_64
arch_bits:64
multiplexing_api:epoll
gcc_version:4.4.7
process_id:2527
run_id:015f1d93aa1684f2adb150828f574d93a657e617
tcp_port:6379
uptime_in_seconds:16355
uptime_in_days:0
hz:10
lru_clock:11824925
executable:/usr/bin/redis-server
config_file:/etc/redis.conf

# Clients
connected_clients:1
client_longest_output_list:0
client_biggest_input_buf:0
blocked_clients:0

# Memory
used_memory:815752
used_memory_human:796.63K
used_memory_rss:4571136
used_memory_rss_human:4.36M
used_memory_peak:148186824
used_memory_peak_human:141.32M
total_system_memory:2050060288
total_system_memory_human:1.91G
used_memory_lua:49152
used_memory_lua_human:48.00K
maxmemory:0
maxmemory_human:0B
maxmemory_policy:noeviction
mem_fragmentation_ratio:5.60
mem_allocator:jemalloc-3.6.0

# Persistence
loading:0
rdb_changes_since_last_save:0
rdb_bgsave_in_progress:0
rdb_last_save_time:1605658689
rdb_last_bgsave_status:ok
rdb_last_bgsave_time_sec:1
rdb_current_bgsave_time_sec:-1
aof_enabled:0
aof_rewrite_in_progress:0
aof_rewrite_scheduled:0
aof_last_rewrite_time_sec:-1
aof_current_rewrite_time_sec:-1
aof_last_bgrewrite_status:ok
aof_last_write_status:ok

# Stats
total_connections_received:40
total_commands_processed:271055
instantaneous_ops_per_sec:0
total_net_input_bytes:11118746
total_net_output_bytes:5534640
instantaneous_input_kbps:0.00
instantaneous_output_kbps:0.00
rejected_connections:0
sync_full:0
sync_partial_ok:0
sync_partial_err:0
expired_keys:0
evicted_keys:0
keyspace_hits:52050
keyspace_misses:1
pubsub_channels:0
pubsub_patterns:0
latest_fork_usec:1835
migrate_cached_sockets:0

# Replication
role:master
connected_slaves:0
master_repl_offset:0
repl_backlog_active:0
repl_backlog_size:1048576
repl_backlog_first_byte_offset:0
repl_backlog_histlen:0

# CPU
used_cpu_sys:8.69
used_cpu_user:8.42
used_cpu_sys_children:2.59
used_cpu_user_children:35.74

# Cluster
cluster_enabled:0

# Keyspace
db0:keys=4,expires=0,avg_ttl=0`

**Comment by rcldesign** [comment]
I should also note, that once the queue disappears, trying to restart the sample code provided causes REDIS to throw:

Unhandled rejection ReplyError: EXECABORT Transaction discarded because of previous errors.
    at parseError (/home/ec2-user/repos/redis-test/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/home/ec2-user/repos/redis-test/node_modules/redis-parser/lib/parser.js:302:14)

This persists, even if the redis server is restarted and requires a reboot of the machine to correct.

**Comment by articleinnovations** [comment]
User error.
