### ISSUE TITLE
Hitting 'message too long' error. At what size does this occur? 

### ISSUE THREAD

**Issue by gebrits** [smrchy/rsmq#15]
Hitting `message too long` as defined in  https://github.com/smrchy/rsmq/blob/deb56ab82f6349b9578bc8d4e15286ca53fa058f/test/test.coffee (could't find other place it's defined in code) 

It this a redis imposed threshold? Do you happen to know the max size?

**Comment by mpneuried** [comment]
see this line of code: https://github.com/smrchy/rsmq/blob/deb56ab82f6349b9578bc8d4e15286ca53fa058f/index.coffee#L152

The default `maxsize` is `65536` chars. But you can change the configuration by setting to option `maxsize`. See docs https://github.com/smrchy/rsmq#createqueue

**Comment by smrchy** [comment]
The `maxsize` setting is just a precaution so that a queue can not make a small Redis server run out of memory. Technically it's possible to store videos, images etc. in the queue but you might want to rethink your design and store these things in S3 or similar systems. Send a small message to RSMQ and let the worker retrieve the blob from your storage (e.g. S3).

**Comment by briangruber** [comment]
Looks like you can't set it over maxsize as there is a check for that range. I created this to help with that for those that need it. #45

**Comment by zubair1024** [comment]
Seems like setting the maxsize to -1 does not work. I'm getting "maxsize must be between 1024 and 65536"

**Comment by mathurs** [comment]
It seems if you have created the queue before setting maxsize, it needs to be deleted from redis and recreated with maxsize. Otherwise you still get this error. Afrer recreating, maxsize -1 works well.
