### ISSUE TITLE
add option to specify id on sendMessage.

### ISSUE THREAD

**Issue by overflowz** [smrchy/rsmq#84]
I need an option to specify id when using sendMessage (optional) while ignoring if message with the same id already exists. I think this will be good option to make sure one message will be sent from multiple running instances (e.g. scheduler). I've been using this from other redis powered queue manager in node and it helped a lot. I switched to RSMQ because it's lightweight and exactly suits my needs atm.

Great work by the way, keep it up 👍

**Comment by overflowz** [comment]
ehm, can we discuss why it has wontfix label?

**Comment by erdii** [comment]
I think because it is a duplicate request. See here: https://github.com/smrchy/rsmq/issues/78

**Comment by overflowz** [comment]
sort-of. except namespacing.

**Comment by erdii** [comment]
I think the reasons for the wontfix are explained here: https://github.com/smrchy/rsmq/issues/78#issuecomment-402739865

**Comment by overflowz** [comment]
IMO this makes queue limited for multi instance application if they all trying to insert same thing, but without controlling the ID, messages would be duplicate (depends on the case). Because of this, I had to implement work-around to share mutex/lock across multiple instances to achieve this.

**Comment by erdii** [comment]
I see what you're trying to achieve, but sadly this is waay too complex for rsmq and our datamodel. 😞 
We need the message id to be generated by rsmq itself because of message ordering and the way we query redis for messages.

Maybe you could avoid the problem of multiple messages triggering "the same thing" on your worker, by using an idempotent operation on the worker, that produces the exact same result again and again.

Read more about it here:
* https://www.c-sharpcorner.com/article/idempotent-operation-in-distributed-system/
* https://en.wikipedia.org/wiki/Idempotence

**Comment by overflowz** [comment]
Yeah, I saw. Wanted to create PR but I realized it was too complex to do that (plus I'm not that familiar with coffeescript). But anyways, thanks for the info! I'll take a look into that.

Closing thread.
